import React, { useEffect, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Button, Copy, Display, Eyebrow, Masthead, Reveal, Section, s, useOtto } from '../../src/ui';
import { colors as c, fonts } from '../../src/theme';
import { otto } from '../../src/data/mock';
import type { DemoScenario, NetworkState } from '../../src/data/types';

const scenarios: {id:DemoScenario;label:string;detail:string}[] = [{id:'default',label:'A day with Otto',detail:'Approvals, connections & action items'},{id:'coffee',label:'Coffee with Sam',detail:'Clarify → calendar → Gmail → approve'},{id:'food',label:'The lunch request',detail:'Simulated food-order approval'},{id:'failure',label:'When a task fails',detail:'A clear record of what went wrong'},{id:'expired',label:'Time ran out',detail:'An expired approval, safely cancelled'},{id:'empty',label:'A quiet moment',detail:'Nothing needs your attention'}];
export default function ConnectionsScreen() {
  const state = useOtto(); const router = useRouter(); const insets = useSafeAreaInsets();
  const [refreshing,setRefreshing] = useState(false); const [settings,setSettings] = useState(false); const [phone,setPhone] = useState('+1 416 555 0142'); const [server,setServer] = useState('https://demo.otto.local'); const [saved,setSaved] = useState(false);
  useEffect(() => {void AsyncStorage.getItem('otto-demo-settings').then(value=>{if(value){const v=JSON.parse(value);setPhone(v.phone);setServer(v.server);}}).catch(()=>{});},[]);
  const recent = [...state.tasks].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).flatMap(t=>t.toolkits_used.map(x=>x.toLowerCase()));
  const extensions = [...state.extensions].sort((a,b)=> {const ai=recent.indexOf(a.id.toLowerCase());const bi=recent.indexOf(b.id.toLowerCase());return (ai<0?999:ai)-(bi<0?999:bi);});
  const connected = extensions.filter(x=>x.status==='connected').length;
  return <View style={[s.page,{paddingTop:insets.top}]}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} tintColor={c.signal} onRefresh={async()=>{setRefreshing(true);try{await otto.getHome();}finally{setRefreshing(false);}}}/>}>
    <Masthead title={'More reach.\nSame Otto.'} subtitle="The tools behind your intentions. You decide what Otto can reach." />
    <View style={{flexDirection:'row',alignItems:'baseline',gap:12,paddingBottom:24,borderBottomWidth:1,borderColor:c.ink}}><Display style={{fontSize:76,letterSpacing:-5}}>{String(connected).padStart(2,'0')}</Display><View style={{flex:1}}><Eyebrow>Connected tools</Eyebrow><Copy style={{color:c.muted,fontSize:13,marginTop:5}}>All connections are simulated.</Copy></View><Feather name="git-merge" size={36} color={c.signal}/></View>
    <View style={{marginTop:26}}><Eyebrow>Recently used first</Eyebrow></View>
    {extensions.map((extension,index)=><Reveal key={extension.id} delay={Math.min(index,3)*50}><View style={s.row}><View style={{flexDirection:'row',alignItems:'flex-start',gap:16}}><View style={{width:42,height:48,alignItems:'center',justifyContent:'center'}}><Feather name={extension.name.toLowerCase().includes('mail')?'mail':extension.name.toLowerCase().includes('calendar')?'calendar':extension.name.toLowerCase().includes('shop')?'shopping-bag':extension.name.toLowerCase().includes('notion')?'file-text':'box'} size={29} color={c.ink}/></View><View style={{flex:1}}><Display style={{fontSize:28}}>{extension.name}</Display><Copy style={{fontSize:13,color:c.muted,marginTop:5}}>{extension.description}</Copy><Copy style={{fontSize:12,color:extension.status==='connected'?c.pine:extension.status==='needs_auth'?c.signal:c.muted,marginTop:10,fontFamily:fonts.medium}}>{extension.status==='connected'?'Connected':extension.status==='needs_auth'?'Needs your connection':'Suggested'} · {extension.tool_count} tools</Copy></View></View><View style={{marginTop:18,marginLeft:58}}>{extension.status==='connected'?<Button label="Disconnect" quiet onPress={()=>otto.disconnect(extension.id)}/>:<Button label={extension.status==='needs_auth'?'Reconnect':'Connect'} icon="arrow-up-right" onPress={()=>router.push({pathname:'/connect/[id]',params:{id:extension.id}})}/>}</View></View></Reveal>)}
    <Section title="Your button." aside="Demo device"/>
    <View style={{backgroundColor:c.ink,padding:24,borderRadius:8}}><View style={{flexDirection:'row',alignItems:'center',gap:20}}><View style={{width:62,height:62,borderRadius:31,borderWidth:1,borderColor:c.muted,alignItems:'center',justifyContent:'center'}}><View style={{width:32,height:32,borderRadius:16,backgroundColor:c.signal}}/></View><View style={{flex:1}}><Display style={{fontSize:27,color:c.bone}}>Otto One</Display><Copy style={{color:c.bone,fontSize:13,marginTop:5}}>{state.network==='online'?'Connected · idle':state.network==='offline'?'Disconnected':'Reconnecting'}</Copy></View></View><View style={{marginTop:24,flexDirection:'row',justifyContent:'space-between'}}><Copy style={{color:c.bone,fontSize:12}}>Last seen: demo session</Copy><Copy style={{color:c.bone,fontSize:12}}>84% battery</Copy></View></View>
    <Section title="Behind the demo."/>
    <Copy style={{color:c.muted,marginBottom:20}}>Local data, real interactions. No messages are sent and no external accounts are changed.</Copy>
    <Button label={settings?'Close settings':'Device & demo settings'} quiet icon={settings?'minus':'plus'} onPress={()=>setSettings(!settings)}/>
    {settings && <Reveal><View style={{paddingTop:26}}><Eyebrow>Demo mode · on</Eyebrow><Copy style={{marginTop:20,marginBottom:8}}>SMS number</Copy><TextInput accessibilityLabel="Demo SMS number" value={phone} onChangeText={v=>{setPhone(v);setSaved(false);}} keyboardType="phone-pad" style={s.input}/><Copy style={{marginTop:18,marginBottom:8}}>Future server URL</Copy><TextInput accessibilityLabel="Future server URL" value={server} onChangeText={v=>{setServer(v);setSaved(false);}} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={s.input}/><Copy style={{color:c.muted,fontSize:12,marginVertical:12}}>Saved on this phone for the demo. No server connection is made.</Copy><Button label={saved?'Settings saved':'Save demo settings'} onPress={async()=>{await AsyncStorage.setItem('otto-demo-settings',JSON.stringify({phone,server}));setSaved(true);}}/>
      <View style={{marginTop:32,marginBottom:14}}><Eyebrow>Connection state</Eyebrow></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{(['online','offline','reconnecting'] as NetworkState[]).map(network=><Pressable key={network} accessibilityRole="button" accessibilityState={{selected:state.network===network}} onPress={()=>otto.setNetwork(network)} style={{paddingHorizontal:14,paddingVertical:12,borderWidth:1,borderColor:c.ink,backgroundColor:state.network===network?c.ink:'transparent',borderRadius:5}}><Copy style={{fontSize:13,color:state.network===network?c.bone:c.ink,textTransform:'capitalize'}}>{network}</Copy></Pressable>)}</View>
      <View style={{marginTop:32,marginBottom:8}}><Eyebrow>Start a scenario</Eyebrow></View><Copy style={{fontSize:13,color:c.muted,marginBottom:10}}>Choosing a story resets tasks, notes and chat to its starting state.</Copy>{scenarios.map(scenario=><View key={scenario.id} style={s.row}><Copy style={{fontSize:17,fontFamily:fonts.medium}}>{scenario.label}</Copy><Copy style={{fontSize:13,color:c.muted,marginTop:4,marginBottom:14}}>{scenario.detail}</Copy><Button label={`Load ${scenario.label}`} quiet icon="rotate-ccw" onPress={async()=>{await otto.reset(scenario.id);router.push('/');}}/></View>)}
    </View></Reveal>}
  </ScrollView></View>;
}
