import { useEffect, useState } from 'react';
import { View, Pressable, RefreshControl, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import Animated, { useAnimatedScrollHandler, useAnimatedStyle, useSharedValue, interpolate, Extrapolation, useReducedMotion } from 'react-native-reanimated';
import { colors as c, fonts } from '../../src/theme';
import { Copy, Display, Eyebrow, Section, Button, Reveal, NetworkBanner, useOtto, s } from '../../src/ui';
import { otto } from '../../src/data/mock';
import type { HomePayload, TaskStatus } from '../../src/data/types';
const labels: Record<TaskStatus,string>={running:'In motion',needs_input:'A quick question',awaiting_approval:'Needs your say',awaiting_connection:'Needs a connection',succeeded:'Done',failed:'Couldn’t finish',cancelled:'Stopped'};
export default function Home() {
 const state=useOtto(); const [home,setHome]=useState<HomePayload>(); const [refreshing,setRefreshing]=useState(false);
 useEffect(()=>{void otto.getHome().then(setHome);},[state]);
 const y=useSharedValue(0); const reduced=useReducedMotion(); const scroll=useAnimatedScrollHandler(e=>{y.value=e.contentOffset.y;});
 const masthead=useAnimatedStyle(()=>({opacity:reduced?1:interpolate(y.value,[0,170],[1,.18],Extrapolation.CLAMP),transform:[{translateY:reduced?0:y.value*.22},{scale:reduced?1:interpolate(y.value,[0,180],[1,.88],Extrapolation.CLAMP)}]}));
 const approvals=home?.approvals??[]; const connections=home?.connections??[]; const actions=home?.action_items??[];
 return <SafeAreaView edges={['top']} style={s.page}><NetworkBanner/><Animated.ScrollView onScroll={scroll} scrollEventThrottle={16} refreshControl={<RefreshControl refreshing={refreshing} tintColor={c.signal} onRefresh={async()=>{setRefreshing(true);setHome(await otto.getHome());setRefreshing(false);}}/>} contentContainerStyle={s.content}>
 <Animated.View style={[h.masthead,masthead]}><View style={h.topline}><Eyebrow>Your everyday, in motion</Eyebrow><Copy style={h.demo}>DEMO</Copy></View><View style={h.wordmark}><Display style={h.otto}>otto</Display><View accessibilityLabel="Otto is ready" style={h.imprint}><View style={h.inner}/></View></View><View style={h.caption}><Copy>Less managing.{'\n'}More living.</Copy><Eyebrow>Heard. Understood.{'\n'}Taken care of.</Eyebrow></View></Animated.View>
 <Section title="Needs you" aside={`${approvals.length+connections.length} waiting`}/>
 {!approvals.length&&!connections.length&&<Reveal style={h.empty}><Display style={{fontSize:34}}>Nothing needs you.</Display><Copy style={{marginTop:12,color:c.muted}}>Otto will let you know when that changes.</Copy></Reveal>}
 {approvals.map((a,i)=><Reveal key={a.id} delay={i*60}><Pressable accessibilityRole="button" accessibilityLabel={`Review ${a.summary}`} onPress={()=>router.push({pathname:'/approval/[id]',params:{id:a.id}})} style={({pressed})=>[h.approval,{opacity:pressed?.9:1}]}><View style={h.topline}><Eyebrow light>Your call</Eyebrow><Feather name="arrow-up-right" size={24} color={c.bone}/></View><Display style={h.approvalTitle}>{a.summary}</Display><View style={h.facts}>{Object.entries(a.facts).slice(0,3).map(([key,value])=><View key={key} style={{flexDirection:'row',justifyContent:'space-between',gap:18}}><Copy style={{color:c.bone,opacity:.8,fontSize:12}}>{key}</Copy><Copy style={{color:c.bone,textAlign:'right',flex:1,fontFamily:fonts.medium}}>{value}</Copy></View>)}</View><View style={h.approvalFoot}><Copy style={{color:c.bone,fontFamily:fonts.medium}}>Review & decide</Copy><View style={h.whiteDot}><Feather name="arrow-right" color={c.signal} size={20}/></View></View></Pressable></Reveal>)}
 {connections.map(a=><Reveal key={a.id} style={h.connection}><Eyebrow>One missing piece</Eyebrow><Display style={{fontSize:29,marginTop:12}}>Let’s connect {a.toolkit}.</Display><Copy style={{color:c.muted,marginTop:10,marginBottom:20}}>Otto needs this tool to continue your request. You stay in control.</Copy><Button label={`Connect ${a.toolkit}`} icon="arrow-up-right" onPress={()=>router.push({pathname:'/connect/[id]',params:{id:a.toolkit}})}/></Reveal>)}
 <Section title="Picked up along the way" aside={`${actions.length}`}/>
 {!actions.length&&<Copy style={{color:c.muted}}>No open action items. Ideas from your conversations will land here.</Copy>}
 {actions.map(a=><Reveal key={a.id} style={s.row}><View style={h.topline}><Eyebrow>Possible next step</Eyebrow><Copy style={{fontSize:12,color:c.muted}}>{Math.round(a.confidence*100)}% confidence</Copy></View><Display style={{fontSize:25,marginTop:12}}>{a.title}</Display><Copy style={{marginTop:12,color:c.muted}}>“{a.snippet}”</Copy><View style={{flexDirection:'row',gap:10,marginTop:20}}><Button label="Do it" icon="arrow-right" onPress={async()=>{const id=await otto.doAction(a.id);router.push({pathname:'/task/[id]',params:{id}});}}/><Button label="Dismiss" quiet onPress={()=>otto.dismissAction(a.id)}/></View></Reveal>)}
 <Section title="The record" aside="Recent activity"/>
 {(home?.recent_tasks??[]).map((task,i)=><Pressable key={task.id} accessibilityRole="button" onPress={()=>router.push({pathname:'/task/[id]',params:{id:task.id}})} style={h.task}><Copy style={{width:25,fontSize:12,color:c.muted}}>{String(i+1).padStart(2,'0')}</Copy><View style={{flex:1,gap:8}}><Copy style={{fontFamily:fonts.medium,fontSize:17}}>{task.goal}</Copy><Copy style={{fontSize:12,color:task.status==='succeeded'?c.pine:c.muted}}>{labels[task.status]} · {task.source.replace('_',' ')}</Copy></View><Feather name="arrow-up-right" color={c.ink} size={19}/></Pressable>)}
 {!home?.recent_tasks.length&&<Copy style={{color:c.muted}}>Your next request starts a new story.</Copy>}
 <View style={{paddingTop:36}}><Eyebrow>Captured in the moment. Handled by Otto.</Eyebrow></View>
 </Animated.ScrollView></SafeAreaView>;
}
const h=StyleSheet.create({masthead:{paddingTop:22,paddingBottom:12},topline:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},demo:{fontSize:10,letterSpacing:1.3,color:c.signal,fontFamily:fonts.medium},wordmark:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingTop:14},otto:{fontSize:120,letterSpacing:-9,lineHeight:138},imprint:{width:82,height:82,borderRadius:41,borderWidth:1,borderColor:c.signal,alignItems:'center',justifyContent:'center',transform:[{rotate:'-25deg'}]},inner:{width:60,height:60,borderRadius:30,backgroundColor:c.signal,borderWidth:7,borderColor:c.bone},caption:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',gap:20},approval:{backgroundColor:c.signal,borderRadius:10,padding:24,marginBottom:16},approvalTitle:{fontSize:35,color:c.bone,marginTop:30,marginBottom:24,lineHeight:38},facts:{gap:12,paddingTop:18,borderTopWidth:1,borderTopColor:'#E57768'},approvalFoot:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:28},whiteDot:{width:40,height:40,borderRadius:20,backgroundColor:c.bone,justifyContent:'center',alignItems:'center'},connection:{borderWidth:1,borderColor:c.line,padding:24,borderRadius:8,marginBottom:12},empty:{paddingVertical:32,borderTopWidth:1,borderBottomWidth:1,borderColor:c.line},task:{flexDirection:'row',gap:12,paddingVertical:24,borderBottomWidth:1,borderColor:c.line}});
