import { useEffect, useState } from 'react';
import { ScrollView, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { colors as c } from '../../src/theme';
import { Copy, Display, Eyebrow, Button, Reveal, useOtto, s } from '../../src/ui';
import { otto } from '../../src/data/mock';
export default function ApprovalScreen() {
 const {id}=useLocalSearchParams<{id:string}>(); const state=useOtto(); const approval=state.approvals.find(a=>a.id===id); const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 if(!approval)return <SafeAreaView style={s.page}><View style={s.content}><Display>Decision unavailable</Display><Button label="Back to Home" onPress={()=>router.replace('/(tabs)/home')}/></View></SafeAreaView>;
 const remaining=Math.max(0,Math.ceil((Date.parse(approval.expires_at)-now)/1000));const pending=approval.status==='pending'&&remaining>0;
 return <SafeAreaView style={[s.page,{backgroundColor:pending?c.signal:c.bone}]}><ScrollView contentContainerStyle={[s.content,{paddingTop:12}]}><Button label="Back" quiet light={pending} onPress={()=>router.back()}/><Reveal><View style={{marginTop:44}}><Eyebrow light={pending}>A moment for your judgment / Demo</Eyebrow><Display style={{fontSize:46,lineHeight:49,color:pending?c.bone:c.ink,marginTop:24}}>{pending?'Your say.\nThen it’s done.':approval.status==='approved'?'You gave the go-ahead.':approval.status==='denied'?'Stopped, as requested.':'This decision expired.'}</Display><Copy style={{color:pending?c.bone:c.muted,marginTop:24,fontSize:20,lineHeight:29}}>{approval.summary}</Copy></View><View style={{marginTop:32,borderTopWidth:1,borderColor:pending?'#E57768':c.line}}>{Object.entries(approval.facts).map(([label,value])=><View key={label} style={{paddingVertical:18,borderBottomWidth:1,borderColor:pending?'#E57768':c.line,gap:6}}><Eyebrow light={pending}>{label}</Eyebrow><Copy selectable style={{color:pending?c.bone:c.ink,fontSize:18}}>{value}</Copy></View>)}</View><Copy style={{color:pending?c.bone:c.muted,marginTop:24,fontSize:13}}>{pending?`Expires in ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}. Only the exact action above is approved.`:'No further action can be taken on this approval.'}</Copy><View style={{gap:12,marginTop:28}}>{pending?<><Button label="Approve this action" light disabled={state.network!=='online'} onPress={async()=>{await otto.approve(id);void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);}}/><Button label="Deny" quiet light disabled={state.network!=='online'} onPress={async()=>{await otto.deny(id);void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);}}/></>:<Button label="See task record" onPress={()=>router.replace({pathname:'/task/[id]',params:{id:approval.task_id}})}/>}</View><Copy style={{fontSize:12,color:pending?c.bone:c.muted,marginTop:24}}>Demo only. This decision changes local sample data. No message, order, or account is affected.</Copy></Reveal></ScrollView></SafeAreaView>;
}
